package org.openprojectx.karate.gradle.task

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Generates two Java source files into [outputDir] that together form the JUnit5
 * entry point used by [RegressionRunTask]:
 *
 * - `KarateRunner` — a JUnit5 `@TestFactory` class that reads its configuration
 *   (feature paths, tag filters) from system properties set by `regressionRun`.
 * - `KarateJUnit5Launcher` — a `main` class that drives the JUnit Platform Launcher,
 *   so that reporter agents (Allure, ReportPortal) that register as JUnit
 *   `TestExecutionListener` implementations are picked up automatically via
 *   ServiceLoader — no explicit wiring required.
 *
 * Both files are compiled into the consumer's test classpath and invoked by
 * `regressionRun` via `javaexec`. Users never need to write or touch these classes.
 *
 * System properties consumed by `KarateRunner` at runtime:
 * | Property                    | Source              |
 * |-----------------------------|---------------------|
 * | `karate.runner.features`    | workflow.features     |
 * | `karate.runner.tags.include`| workflow.tags.include |
 * | `karate.runner.tags.exclude`| workflow.tags.exclude |
 */
abstract class GenerateKarateRunnerTask : DefaultTask() {

    /** Root of the generated sources tree — wired into the `test` Java source set. */
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val packagePath = "org/openprojectx/karate/runner"
        val packageDir = outputDir.get().asFile.resolve(packagePath)
        packageDir.mkdirs()

        packageDir.resolve("KarateRunner.java").writeText(karateRunnerSource())
        packageDir.resolve("KarateJUnit5Launcher.java").writeText(launcherSource())
    }

    // ─────────────────────────────────────────────────────────────────────────

    private fun karateRunnerSource() = """
        package org.openprojectx.karate.runner;

        import com.intuit.karate.junit5.Karate;
        import org.junit.jupiter.api.DynamicNode;
        import org.junit.jupiter.api.TestFactory;
        import java.util.ArrayList;
        import java.util.List;

        /**
         * Auto-generated by karate-gradle. Do not edit.
         *
         * Uses {@code @TestFactory} so that each Karate feature becomes a
         * {@code DynamicContainer} and each scenario becomes a {@code DynamicTest}.
         * This lets reporter agents (Allure, ReportPortal) capture per-scenario results
         * via the JUnit Platform listener API.
         *
         * Reads its configuration from system properties injected by {@code regressionRun}:
         * <ul>
         *   <li>{@code karate.runner.features}     — comma-separated feature paths</li>
         *   <li>{@code karate.runner.tags.include}  — comma-separated include tags</li>
         *   <li>{@code karate.runner.tags.exclude}  — comma-separated exclude tags</li>
         * </ul>
         */
        class KarateRunner {

            @TestFactory
            Iterable<DynamicNode> all() {
                String features = System.getProperty("karate.runner.features", "classpath:features");
                Karate runner = Karate.run(features.split(",")).relativeTo(getClass());

                List<String> tags = new ArrayList<>();
                String include = System.getProperty("karate.runner.tags.include", "");
                String exclude = System.getProperty("karate.runner.tags.exclude", "");
                if (!include.isEmpty()) {
                    for (String t : include.split(",")) tags.add(t.trim());
                }
                if (!exclude.isEmpty()) {
                    for (String t : exclude.split(",")) tags.add("~" + t.trim());
                }
                if (!tags.isEmpty()) {
                    runner = runner.tags(tags.toArray(new String[0]));
                }

                return runner;
            }
        }
    """.trimIndent()

    private fun launcherSource() = """
        package org.openprojectx.karate.runner;

        import org.junit.platform.engine.TestExecutionResult;
        import org.junit.platform.engine.discovery.DiscoverySelectors;
        import org.junit.platform.launcher.LauncherDiscoveryRequest;
        import org.junit.platform.launcher.LauncherSession;
        import org.junit.platform.launcher.TestExecutionListener;
        import org.junit.platform.launcher.TestIdentifier;
        import org.junit.platform.launcher.core.LauncherDiscoveryRequestBuilder;
        import org.junit.platform.launcher.core.LauncherFactory;
        import java.io.PrintWriter;
        import java.lang.reflect.Method;
        import java.util.concurrent.atomic.AtomicInteger;

        /**
         * Auto-generated by karate-gradle. Do not edit.
         *
         * Main class invoked by {@code regressionRun} via {@code javaexec}. Drives the
         * JUnit Platform Launcher via {@link LauncherFactory#openSession()} so that
         * reporter agents registered as {@code LauncherSessionListener} or
         * {@code TestExecutionListener} implementations (Allure, ReportPortal) are
         * discovered automatically via ServiceLoader — no explicit wiring required.
         *
         * Exits with code 1 if any test fails; 0 otherwise.
         */
        public class KarateJUnit5Launcher {

            public static void main(String[] args) {
                AtomicInteger failures = new AtomicInteger();

                LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
                        .selectors(DiscoverySelectors.selectClass(
                                "org.openprojectx.karate.runner.KarateRunner"))
                        .build();

                // openSession() is required so that LauncherSessionListener implementations
                // (e.g. AllureJunitPlatform) receive their session lifecycle callbacks.
                try (LauncherSession session = LauncherFactory.openSession()) {
                    session.getLauncher().execute(request, new TestExecutionListener() {
                        @Override
                        public void executionFinished(TestIdentifier id, TestExecutionResult result) {
                            if (result.getStatus() == TestExecutionResult.Status.FAILED) {
                                failures.incrementAndGet();
                                result.getThrowable().ifPresent(t ->
                                        t.printStackTrace(new PrintWriter(System.err, true)));
                            }
                        }
                    });
                } finally {
                    runCleanupHook();
                }

                if (failures.get() > 0) {
                    System.exit(1);
                }
            }

            private static void runCleanupHook() {
                String cleanupClass = System.getProperty("karate.cleanup.class", "").trim();
                if (cleanupClass.isEmpty()) {
                    return;
                }
                try {
                    Class<?> type = Class.forName(cleanupClass);
                    Method stop = type.getMethod("stop");
                    stop.invoke(null);
                } catch (Exception e) {
                    throw new RuntimeException("Failed to invoke cleanup hook: " + cleanupClass, e);
                }
            }
        }
    """.trimIndent()
}
