package org.openprojectx.karate.gradle.task

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Generates a JUnit5 runner class that feeds Karate results into the active
 * reporting agents (Allure, ReportPortal).
 *
 * The generated class lives in [outputDir] under the internal package
 * `org.openprojectx.karate.runner` so it never conflicts with consumer code.
 * The plugin wires [outputDir] into the `test` source set automatically.
 *
 * Users never touch this class — it is registered and executed by the plugin
 * when `allure.enabled` or `reportPortal.enabled` is `true`.
 */
abstract class GenerateKarateRunnerTask : DefaultTask() {

    /** Karate feature path, e.g. `classpath:features`. */
    @get:Input
    abstract val featuresPath: Property<String>

    /**
     * Tags to include (e.g. `["@regression", "@smoke"]`).
     * Empty list = no include filter.
     */
    @get:Input
    abstract val includeTags: ListProperty<String>

    /**
     * Tags to exclude (e.g. `["@ignore", "@replay"]`).
     * Empty list = no exclude filter.
     */
    @get:Input
    abstract val excludeTags: ListProperty<String>

    /** Root of the generated sources tree. Added to `test` Java source set by the plugin. */
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val packagePath = "org/openprojectx/karate/runner"
        val packageDir = outputDir.get().asFile.resolve(packagePath)
        packageDir.mkdirs()

        val features = featuresPath.get()
        val include = includeTags.get()
        val exclude = excludeTags.get()

        // Build the fluent Karate.run(...) chain
        val runChain = buildString {
            append("""Karate.run("$features").relativeTo(getClass())""")
            if (include.isNotEmpty()) {
                val tags = include.joinToString(", ") { "\"$it\"" }
                append(".tags($tags)")
            }
            if (exclude.isNotEmpty()) {
                // Karate excludes a tag by prefixing with ~
                val tags = exclude.joinToString(", ") { "\"~$it\"" }
                append(".tags($tags)")
            }
        }

        packageDir.resolve("KarateRunner.java").writeText(
            """
            package org.openprojectx.karate.runner;

            import com.intuit.karate.junit5.Karate;

            /**
             * Auto-generated by karate-gradle. Do not edit.
             *
             * This class is the JUnit5 entry point that activates reporting agents
             * (Allure, ReportPortal) when running {@code ./gradlew test}.
             * It is generated into the build directory and never checked in.
             */
            class KarateRunner {

                @Karate.Test
                Karate all() {
                    return $runChain;
                }
            }
            """.trimIndent()
        )
    }
}
